### ISSUE TITLE
Affichage des résultats de groupe (cortical)

### ISSUE THREAD

**Issue by annesodub** [annesodub/ABRBABY#13]
- [ ] Ajouter un filtre d'affichage pour les timecourses : 10Hz
- [ ] Vérifier la convention de couleur (différences en noir), consistent code for conditions (please @estellerv provide snapshot)
- [ ] Grid on?
- [ ] Negative up?

**Comment by estellerv** [comment]
Done, seePR #19 

Snapshots for colors update:

![image](https://user-images.githubusercontent.com/67378186/198526955-44e2325d-95d8-43a4-89c9-a66ca28757c4.png)

![image](https://user-images.githubusercontent.com/67378186/198526984-affb14d0-6f77-4bb7-b6c4-c57b43214cb5.png)

**Comment by annesodub** [comment]
@estellerv : Attention de bien ajuster les échelles pour qu'elles soient les même sur tous les subplots!
