### ISSUE TITLE
Affichage résultat de groupe (FFR) 

### ISSUE THREAD

**Issue by annesodub** [annesodub/ABRBABY#14]
@estellerv : peux-tu nous montrer un snapshot please?

**Comment by estellerv** [comment]
Yes sure @annesodub ! (colors to change eventually)

![image](https://user-images.githubusercontent.com/67378186/197986507-ac9ae87d-f4df-4e24-be97-b48d004d7be7.png)
Snapshot of the grand average FFR (time domain)


![image](https://user-images.githubusercontent.com/67378186/197987603-00c0912e-54c5-4479-9e6d-de6ed2af70df.png)
Snaphot of the grand average FFR by age group (time domain


![image](https://user-images.githubusercontent.com/67378186/197987641-067fcfa9-784c-42e8-a009-db9615bcf841.png)
Snapshot of the frequential domain of the grand average FFR

**Comment by annesodub** [comment]
thank you @estellerv! Looks good to me. What function did you use to generate these?

**Comment by annesodub** [comment]
Well done!
