### ISSUE TITLE
Créer les fonctions d'appels (script_Estelle script_AnneSo) 

### ISSUE THREAD

**Issue by annesodub** [annesodub/ABRBABY#15]
et dégager les path des fonction princpales (e.g. INDIR = '/Users/anne-sophiedubarry/Documents/0_projects/in_progress/ABRBABY_cfrancois/data/DEVLANG_data/' ;) 

pour ne pas galérer à les modifier à chaque fois que quelqu'un modifie la fonction...

**Comment by annesodub** [comment]
this is addressed in https://github.com/annesodub/ABRBABY/pull/16

**Comment by estelle** [comment]
Wrong Estelle.
